baseURL = "/"
languageCode = "en-us"
title = "Choon Kiat (CK)"

theme = "lanyon"

DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true

# DisqusShortname = "choonkiatlee"

[params]
  Title = "Curious Koala"
  # Tagline = "Choon Kiat (CK)"
  Author = "Choon Kiat (CK)"
  profilePicture = "images/curious-koala.png"
  DateForm = "2 Jan 2006"
  mainSections = [
    "posts"
  ]
  description = "Just another curious koala clinging on to the pursuit of knowledge"

  enableUtterance = true



# Deal with links
canonifyurls = false
[permalinks]
  post = ":year/:month/:day/:title/"
  fixed = ":title/"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[menu]

  [[menu.main]]
  name = "Posts"
  identifier = "posts"
  title = "Posts"
  weight = 100
  url = "/posts/"

  [[menu.main]]
  name = "TIL"
  identifier = "TIL"
  title = "TIL (Today I Learned)"
  weight = 200
  url = "/til/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"

  [[menu.main]]
  name = "Projects"
  identifier = "projects"
  title = "Projects"
  weight = 400
  url = "/projects/"

  [[menu.main]]
  name = "Categories"
  identifier = "categories"
  pre = "toptitlebar-false"           # Note that this is a hack used to indicate that this menu shouldn't be displayed on the top titlebar  
  title = "Categories Section"
  weight = 500
  url = "/categories/"

[markup]

  # [markup.goldmark]
  #   [goldmark.extensions]
  #     typographer = true
  #   [goldmark.renderer]
  #     unsafe=true

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

